"""add billing models

Revision ID: a83b4b7a3211
Revises: b3a09c049e8e
Create Date: 2023-11-03 15:51:10.925759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a83b4b7a3211'
down_revision = 'b3a09c049e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balances',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('point', sa.Integer(), nullable=False),
    sa.Column('account_id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='balance_pkey')
    )
    with op.batch_alter_table('balances', schema=None) as batch_op:
        batch_op.create_index('balance_account_id_idx', ['account_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('currency', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('point', sa.Integer(), nullable=False),
    sa.Column('account_id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='order_pkey')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('order_account_id_idx', ['account_id'], unique=False)

    op.drop_table('sessions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey'),
    sa.UniqueConstraint('session_id', name='sessions_session_id_key')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('order_account_id_idx')

    op.drop_table('orders')
    with op.batch_alter_table('balances', schema=None) as batch_op:
        batch_op.drop_index('balance_account_id_idx')

    op.drop_table('balances')
    # ### end Alembic commands ###
